### ISSUE TITLE
The first iteration reporting WPS is inaccurate because of extra initialization work

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#92]
Hey,

When training, the first tick that shows the WPS rate and the error is inaccurate because it also includes initialization work which happens there. There should either be a disclaimer about it, or the initialization work should not be included (as it happens only once).

Cheers,

Nick

**Comment by emjotde** [comment]
The easy way to fix this would be to reset all counters after the N first batches, where N is the number of GPUs it is runs on.

**Comment by snukky** [comment]
Should be fixed with 0fa3e9342b7f1e35c7dd423906141a718b951acb and c20758ab4e9bbeaf1a72d75db118200f56612333.

**Comment by emjotde** [comment]
It's now not too slow but too fast :)

**Comment by snukky** [comment]
I confirm that sometimes values are too high, but I haven't figured yet why. I'm working on that.

As a reminder for myself: the time/WPS calculation may be still too high if training is restarted in the middle of an epoch.

**Comment by emjotde** [comment]
Reverting the changes associated with this issue for now. This is much less trivial than intially thought and current fixes actually look more buggy (missing sentence counts etc.). I am still not sure I am actually too concerned about this, since the iterations do actually take longer due to lazy inits.

**Comment by emjotde** [comment]
I would close this. I am seeing similar behaviour in other toolkits too.
